
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: demo-metrics-app
  namespace: demo
  labels:
    release: monitoring
spec:
  selector:
    matchLabels:
      app: demo-metrics-app
  namespaceSelector:
    matchNames:
      - demo
  endpoints:
    - port: http
      path: /metrics
      interval: 15s
